"""empty message

Revision ID: 951b6aa47d6d
Revises: 
Create Date: 2026-04-21 17:10:42.611377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951b6aa47d6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('filename',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_info', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
